using Skugga.Core;
using Xunit;

namespace Skugga.OpenApi.Tests
{
#if ENABLE_URL_DOWNLOAD_TESTS
    // This interface should be generated from the downloaded USPTO spec
    // NOTE: Must be top-level (not nested in class) for source generator to find it
    // Disabled in CI/CD - enable locally by defining ENABLE_URL_DOWNLOAD_TESTS
    [SkuggaFromOpenApi("https://raw.githubusercontent.com/OAI/learn.openapis.org/refs/heads/main/examples/v3.0/uspto.json")]
    public partial interface IUsptoApi
    {
    }

    /// <summary>
    /// Tests for URL downloading functionality.
    /// Uses USPTO (US Patent and Trademark Office) API spec from OAI GitHub repository.
    /// NOTE: Requires TWO builds - first build downloads spec, second build generates code.
    /// This is by design due to MSBuild evaluation vs execution phase timing.
    /// DISABLED IN CI/CD - requires network access during build.
    /// </summary>
    public class UrlDownloadingTests
    {
        [Fact]
        [Trait("Category", "Integration")]
        public void Interface_ExistsAfterUrlDownload()
        {
            // If URL downloading works, this interface should be generated
            var interfaceType = typeof(IUsptoApi);
            Assert.NotNull(interfaceType);
        }

        [Fact]
        [Trait("Category", "Integration")]
        public void Interface_HasMethods()
        {
            // The USPTO API should have operations
            var interfaceType = typeof(IUsptoApi);
            var methods = interfaceType.GetMethods();

            Assert.NotEmpty(methods);

            // Verify we got some methods generated from the spec
            Assert.True(methods.Length > 0, $"Expected > 0 methods, got {methods.Length}");
        }

        [Fact]
        [Trait("Category", "Integration")]
        public void Mock_CanBeCreated()
        {
            // Mock class should also be generated by OpenAPI generator
            var mock = new IUsptoApiMock();
            Assert.NotNull(mock);

            // Verify mock implements the interface
            IUsptoApi api = mock;
            Assert.NotNull(api);
        }
    }
#endif
}
