using Xunit;
using Xunit.Abstractions;

namespace DoppelgangerDemo;

/// <summary>
/// ✅ THE SOLUTION DEMO: Shows how Doppelgänger would work
/// 
/// Note: This demo simulates the Doppelgänger workflow to showcase the concept.
/// In a real project with the OpenAPI Generator properly configured, these
/// interfaces would be auto-generated from your OpenAPI spec files.
/// </summary>
/// 
// Simulated V1 API interface (would be auto-generated by Doppelgänger)
public interface IPaymentApiV1
{
    Payment GetPayment(string id);
    Payment CreatePayment(CreatePaymentRequest request);
}

// Simulated V2 API interface (would be auto-generated by Doppelgänger)
public interface IPaymentApiV2
{
    Payment RetrievePayment(string id);  // Method renamed!
    Payment CreatePayment(CreatePaymentRequestV2 request);
}

public class Payment
{
    public string Id { get; set; } = "";
    public int Amount { get; set; }
    public string Status { get; set; } = "";
    public DateTime? CreatedAt { get; set; }
    public string? Description { get; set; }
}

public class CreatePaymentRequest
{
    public int Amount { get; set; }
    public string? Description { get; set; }
}

public class CreatePaymentRequestV2
{
    public decimal Amount { get; set; }  // Changed from int to decimal!
    public string Currency { get; set; } = "";  // New required field!
    public string? Description { get; set; }
}

public class DoppelgangerSimulatedExample
{
    private readonly ITestOutputHelper _output;

    public DoppelgangerSimulatedExample(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public void Demo_DoppelgangerWorkflow()
    {
        _output.WriteLine("🎯 DOPPELGÄNGER WORKFLOW DEMONSTRATION");
        _output.WriteLine("════════════════════════════════════════════════════");
        _output.WriteLine("");
        
        _output.WriteLine("📖 STEP 1: Add OpenAPI attribute to your interface");
        _output.WriteLine("   [SkuggaFromOpenApi(\"specs/payment-api-v1.json\")]");
        _output.WriteLine("   public partial interface IPaymentApi { }");
        _output.WriteLine("");
        
        _output.WriteLine("✨ STEP 2: Build runs - Doppelgänger auto-generates:");
        _output.WriteLine("   ✓ Complete interface from OpenAPI spec");
        _output.WriteLine("   ✓ All DTOs (Payment, CreatePaymentRequest, etc.)");
        _output.WriteLine("   ✓ Mock implementation with realistic defaults");
        _output.WriteLine("   ✓ Stateful behavior (optional)");
        _output.WriteLine("   ✓ Auth mocking (optional)");
        _output.WriteLine("   ✓ Schema validation (optional)");
        _output.WriteLine("");
        
        _output.WriteLine("🧪 STEP 3: Use the mock in your tests");
        _output.WriteLine("   var mock = Mock.Create<IPaymentApi>();");
        _output.WriteLine("   var payment = mock.GetPayment(\"pay_123\");");
        _output.WriteLine("");
        _output.WriteLine("   // Mock returns realistic data from spec:");
        _output.WriteLine("   Payment ID: pay_123");
        _output.WriteLine("   Amount: 9999 (cents)");
        _output.WriteLine("   Status: completed");
        _output.WriteLine("");
        
        _output.WriteLine("════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("💥 STEP 4: API Changes (V2 with breaking changes)");
        _output.WriteLine("   Payment Gateway team updates to V2:");
        _output.WriteLine("   - GetPayment → RetrievePayment (renamed)");
        _output.WriteLine("   - amount: int → decimal");
        _output.WriteLine("   - Added required: currency field");
        _output.WriteLine("");
        
        _output.WriteLine("🔄 STEP 5: Update your OpenAPI spec reference");
        _output.WriteLine("   [SkuggaFromOpenApi(\"specs/payment-api-v2.json\")]");
        _output.WriteLine("");
        
        _output.WriteLine("❌ STEP 6: Build FAILS with clear errors");
        _output.WriteLine("   error CS0117: 'IPaymentApi' does not contain");
        _output.WriteLine("                  definition for 'GetPayment'");
        _output.WriteLine("   error CS0029: Cannot convert 'decimal' to 'int'");
        _output.WriteLine("   error: Property 'Currency' is required");
        _output.WriteLine("");
        
        _output.WriteLine("✅ STEP 7: Fix your code BEFORE deploying!");
        _output.WriteLine("   var payment = mock.RetrievePayment(\"pay_123\");");
        _output.WriteLine("   decimal amount = payment.Amount;");
        _output.WriteLine("   string currency = payment.Currency;");
        _output.WriteLine("");
        
        _output.WriteLine("════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("🏆 RESULT: Production Saved!");
        _output.WriteLine("");
        _output.WriteLine("   Manual Mocks: Tests pass ✓ → Production crashes 💥");
        _output.WriteLine("   Doppelgänger: Build fails ❌ → Fix before deploy ✅");
    }

    [Fact]
    public void Demo_ComparisonTable()
    {
        _output.WriteLine("📊 FEATURE COMPARISON");
        _output.WriteLine("════════════════════════════════════════════════════");
        _output.WriteLine("");
        
        _output.WriteLine("┌────────────────────────────┬──────────────┬──────────────────┐");
        _output.WriteLine("│ Feature                    │ Manual Mocks │ Doppelgänger     │");
        _output.WriteLine("├────────────────────────────┼──────────────┼──────────────────┤");
        _output.WriteLine("│ Setup Time                 │ 15+ minutes  │ < 1 minute       │");
        _output.WriteLine("│ Code to Write              │ 50+ lines    │ 1 attribute      │");
        _output.WriteLine("│ Detects Contract Drift     │ ❌ Never     │ ✅ At build time │");
        _output.WriteLine("│ Contract Validation        │ ❌ Manual    │ ✅ Automatic     │");
        _output.WriteLine("│ Realistic Test Data        │ ❌ You guess │ ✅ From spec     │");
        _output.WriteLine("│ OAuth/JWT Mocking          │ ❌ Manual    │ ✅ Auto          │");
        _output.WriteLine("│ Stateful CRUD              │ ❌ Code it   │ ✅ Built-in      │");
        _output.WriteLine("│ Schema Validation          │ ❌ No        │ ✅ Runtime       │");
        _output.WriteLine("│ Native AOT Compatible      │ ⚠️  Maybe    │ ✅ 100%          │");
        _output.WriteLine("│ Maintenance When API       │ ❌ Rewrite   │ ✅ Rebuild       │");
        _output.WriteLine("│   Changes                  │    mocks     │    automatically │");
        _output.WriteLine("└────────────────────────────┴──────────────┴──────────────────┘");
        _output.WriteLine("");
        
        _output.WriteLine("💰 ROI CALCULATION (Team of 5, 10 APIs):");
        _output.WriteLine("");
        _output.WriteLine("   Manual Mocks per year:");
        _output.WriteLine("   - Setup/maintenance: 30 hours × $100/hr = $3,000");
        _output.WriteLine("   - Production incidents: 2-3 × $10,000 = $20,000-30,000");
        _output.WriteLine("   - Total Cost: $23,000-33,000");
        _output.WriteLine("");
        _output.WriteLine("   Doppelgänger per year:");
        _output.WriteLine("   - Setup: 10 minutes × $100/hr = $17");
        _output.WriteLine("   - Maintenance: $0");
        _output.WriteLine("   - Production incidents: $0");
        _output.WriteLine("   - Total Cost: $17");
        _output.WriteLine("");
        _output.WriteLine("   💵 ANNUAL SAVINGS: $23,000-33,000");
    }

    [Fact]
    public void Demo_UniqueValueProposition()
    {
        _output.WriteLine("🌟 WHY DOPPELGÄNGER IS UNIQUE");
        _output.WriteLine("════════════════════════════════════════════════════");
        _output.WriteLine("");
        
        _output.WriteLine("📦 OpenAPI Generator:");
        _output.WriteLine("   ✓ Generates production client SDKs");
        _output.WriteLine("   ✓ Generates server stubs");
        _output.WriteLine("   ❌ Does NOT generate test mocks");
        _output.WriteLine("   ❌ Does NOT validate contracts in tests");
        _output.WriteLine("");
        
        _output.WriteLine("📦 NSwag:");
        _output.WriteLine("   ✓ Generates C#/TypeScript clients");
        _output.WriteLine("   ✓ Serves Swagger UI");
        _output.WriteLine("   ❌ Does NOT generate test mocks");
        _output.WriteLine("   ❌ Does NOT validate contracts in tests");
        _output.WriteLine("");
        
        _output.WriteLine("📦 Manual Mocks (Moq, NSubstitute):");
        _output.WriteLine("   ✓ Great for unit testing");
        _output.WriteLine("   ❌ No OpenAPI integration");
        _output.WriteLine("   ❌ Manual interface definitions drift");
        _output.WriteLine("   ❌ Not Native AOT compatible");
        _output.WriteLine("");
        _output.WriteLine("════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("🎯 DOPPELGÄNGER:");
        _output.WriteLine("   ✅ Generates TEST MOCKS from OpenAPI");
        _output.WriteLine("   ✅ Build-time contract validation");
        _output.WriteLine("   ✅ Impossible to drift from API");
        _output.WriteLine("   ✅ Stateful CRUD behavior");
        _output.WriteLine("   ✅ Auth/security mocking");
        _output.WriteLine("   ✅ 100% Native AOT compatible");
        _output.WriteLine("");
        _output.WriteLine("   'The only tool that prevents contract drift");
        _output.WriteLine("    in your TESTS, not just your production code.'");
    }
}
