#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skugga.Generator
{
    internal static class GeneratorHelpers
    {
        public const string AutoGeneratedComment = "// <auto-generated/>";
        public const string NullableEnable = "#nullable enable";
        public const string SystemUsing = "using System;";
        public const string SkuggaCoreUsing = "using Skugga.Core;";
        public const string SkuggaGeneratedNamespace = "namespace Skugga.Generated";
        public const string MockHandlerField = "private readonly MockHandler _handler = new();";
        public const string HandlerProperty = "public MockHandler Handler => _handler;";
        public const string ArrayEmpty = "Array.Empty<object?>()";

        /// <summary>
        /// Formats a compile-time constant as a C# literal for emission into generated source.
        /// </summary>
        /// <remarks>
        /// Every numeric conversion here must use <see cref="CultureInfo.InvariantCulture"/>.
        /// Generated source code is C#, not user-facing text, and C# literals are defined in terms
        /// of the invariant culture regardless of the machine running the compiler.
        ///
        /// This previously used culture-sensitive interpolation. On a machine whose culture uses
        /// ',' as the decimal separator, a setup written as <c>CalculateDiscount(999.99m, "x")</c>
        /// emitted <c>999,99m</c> into the argument array, which the compiler read as *two*
        /// arguments. The argument count then never matched the real invocation, so the setup
        /// silently did not apply and the mock returned <c>default</c> -- with no compiler error
        /// and no exception. Round-trip ("R") formatting is used for float and double so the
        /// literal reconstructs the exact value.
        /// </remarks>
        public static string FormatConstantValue(object? value)
        {
            if (value == null) return "null";
            if (value is string s) return $"\"{s.Replace("\"", "\\\"")}\"";
            if (value is bool b) return b ? "true" : "false";
            if (value is char c) return $"'{c}'";
            if (value is decimal m) return m.ToString(CultureInfo.InvariantCulture) + "m";
            if (value is float f) return f.ToString("R", CultureInfo.InvariantCulture) + "f";
            if (value is double d) return d.ToString("R", CultureInfo.InvariantCulture) + "d";
            if (value is long l) return l.ToString(CultureInfo.InvariantCulture) + "L";
            if (value is ulong ul) return ul.ToString(CultureInfo.InvariantCulture) + "UL";
            // Remaining integral types: still format invariantly, because the negative sign is
            // itself culture-dependent.
            if (value is IFormattable formattable) return formattable.ToString(null, CultureInfo.InvariantCulture);
            return value.ToString() ?? "null";
        }

        public static string GetStableHash(string text)
        {
            const uint fnvPrime = 0x01000193;
            uint hash = 0x811c9dc5;
            foreach (char c in text)
            {
                hash ^= c;
                hash *= fnvPrime;
            }
            return hash.ToString();
        }

        public static IEnumerable<IMethodSymbol> GetAllMethods(INamedTypeSymbol symbol)
        {
            var members = new List<IMethodSymbol>();
            var visited = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
            var stack = new Stack<INamedTypeSymbol>();
            stack.Push(symbol);

            while (stack.Count > 0)
            {
                var current = stack.Pop();
                if (current == null || !visited.Add(current)) continue;

                members.AddRange(current.GetMembers().OfType<IMethodSymbol>());

                if (current.BaseType != null)
                    stack.Push(current.BaseType);

                foreach (var i in current.Interfaces)
                    stack.Push(i);
            }

            return members;
        }

        public static IEnumerable<IPropertySymbol> GetAllProperties(INamedTypeSymbol symbol)
        {
            var members = new List<IPropertySymbol>();
            var visited = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
            var stack = new Stack<INamedTypeSymbol>();
            stack.Push(symbol);

            while (stack.Count > 0)
            {
                var current = stack.Pop();
                if (current == null || !visited.Add(current)) continue;

                members.AddRange(current.GetMembers().OfType<IPropertySymbol>());

                if (current.BaseType != null)
                    stack.Push(current.BaseType);

                foreach (var i in current.Interfaces)
                    stack.Push(i);
            }

            return members;
        }

        public static IEnumerable<IEventSymbol> GetAllEvents(INamedTypeSymbol symbol)
        {
            var members = new List<IEventSymbol>();
            var visited = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
            var stack = new Stack<INamedTypeSymbol>();
            stack.Push(symbol);

            while (stack.Count > 0)
            {
                var current = stack.Pop();
                if (current == null || !visited.Add(current)) continue;

                members.AddRange(current.GetMembers().OfType<IEventSymbol>());

                if (current.BaseType != null)
                    stack.Push(current.BaseType);

                foreach (var i in current.Interfaces)
                    stack.Push(i);
            }

            return members;
        }

        public static bool IsRefStructOrContainsRefStruct(ITypeSymbol type)
        {
            if (type.IsRefLikeType) return true;
            if (type is INamedTypeSymbol named && named.IsGenericType)
            {
                return named.TypeArguments.Any(IsRefStructOrContainsRefStruct);
            }
            return false;
        }

        public static string GetDefaultValueForType(ITypeSymbol returnType, string returnTypeDisplayString)
        {
            if (returnType.SpecialType == SpecialType.System_Void) return "null";

            var typeStr = returnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return $"typeof({typeStr})";
        }

        public static void GenerateModuleInitializer(SourceProductionContext spc, List<(string BaseType, string MockClassName)> generatedMocks)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine(AutoGeneratedComment);
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine(SkuggaCoreUsing);
            sb.AppendLine();
            sb.AppendLine(SkuggaGeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    internal static class SkuggaInit");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        internal static void Initialize()");
            sb.AppendLine("        {");

            foreach (var (baseType, mockClassName) in generatedMocks)
            {
                sb.AppendLine($"            MockDefaultValueProvider.RegisterMockFactory<{baseType}>(() => new {mockClassName}(DefaultValue.Mock));");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("SkuggaInit.g.cs", Microsoft.CodeAnalysis.Text.SourceText.From(sb.ToString(), System.Text.Encoding.UTF8));
        }
    }
}
