#nullable enable
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using static Skugga.Generator.GeneratorHelpers;

namespace Skugga.Generator
{
    internal static class HarnessGenerator
    {
        public static void GenerateHarnessClass(SourceProductionContext spc, TargetInfo target)
        {
            var symbol = target.Symbol;
            if (symbol == null) return;

            var stableHash = GetStableHash(symbol.ToDisplayString());
            var className = $"Harness_{symbol.Name}_{stableHash}";
            var baseType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var sb = new StringBuilder(4096);
            sb.AppendLine(AutoGeneratedComment);
            sb.AppendLine(NullableEnable);
            sb.AppendLine(SystemUsing);
            sb.AppendLine(SkuggaCoreUsing);
            sb.AppendLine();
            sb.AppendLine(SkuggaGeneratedNamespace);
            sb.AppendLine("{");
            sb.Append("    public class ");
            sb.Append(className);
            sb.Append(" : global::Skugga.Core.TestHarness<");
            sb.Append(baseType);
            sb.AppendLine(">");
            sb.AppendLine("    {");
            sb.Append("        public ");
            sb.Append(className);
            sb.AppendLine("()");
            sb.AppendLine("        {");

            // Find longest constructor
            var ctor = symbol.Constructors
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();

            if (ctor != null)
            {
                var args = new System.Collections.Generic.List<string>();
                foreach (var param in ctor.Parameters)
                {
                    var paramType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    // Basic heuristic: check if it's an interface we can mock
                    if (param.Type.TypeKind == TypeKind.Interface)
                    {
                        var mockVar = $"mock_{param.Name}";
                        sb.AppendLine($"            var {mockVar} = global::Skugga.Core.Mock.Create<{paramType}>();");
                        sb.AppendLine($"            _mocks[typeof({paramType})] = {mockVar};");
                        args.Add(mockVar);
                    }
                    else
                    {
                        // Default for non-mockable types
                        args.Add($"default({paramType})!");
                    }
                }

                sb.AppendLine();
                sb.Append("            SUT = new ");
                sb.Append(baseType);
                sb.Append("(");
                sb.Append(string.Join(", ", args));
                sb.AppendLine(");");
            }
            else
            {
                // No constructor or empty? Just new()
                sb.AppendLine($"            SUT = new {baseType}();");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
