#nullable enable
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using static Skugga.Generator.GeneratorHelpers;

namespace Skugga.Generator
{
    internal static class InterceptorGenerator
    {
        public static void GenerateInterceptor(SourceProductionContext spc, TargetInfo target)
        {
            var symbol = target.Symbol;
            if (symbol == null) return;

            var stableHash = GetStableHash(symbol.ToDisplayString());
            var className = $"Skugga_{symbol.Name}_{stableHash}";
            var interceptorName = $"Interceptor_{className}";
            var filePath = target.Location.SourceTree?.FilePath ?? "";
            var lineSpan = target.Location.GetLineSpan();
            var line = lineSpan.StartLinePosition.Line + 1;
            var charPos = lineSpan.StartLinePosition.Character + 1;

            var fullTypeName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var isHarness = target.Type == TargetType.Harness;
            var isAutoScribe = target.Type == TargetType.AutoScribe;

            // Unique name for this specific call site
            var uniqueId = GetStableHash($"{filePath}_{line}_{charPos}");
            var interceptorClassName = $"{interceptorName}_{uniqueId}";

            var sb = new StringBuilder(1024);
            sb.AppendLine(AutoGeneratedComment);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("#pragma warning disable CS9270");
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
            sb.AppendLine("    file sealed class InterceptsLocationAttribute : Attribute");
            sb.AppendLine("    {");
            sb.AppendLine("        public InterceptsLocationAttribute(string filePath, int line, int character) { }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine(SkuggaGeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {interceptorClassName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(@\"{filePath}\", {line}, {charPos})]");

            if (isHarness)
            {
                sb.AppendLine($@"        public static global::Skugga.Core.TestHarness<T> Create<T>()
        {{
            return new global::Skugga.Core.TestHarness<T>((global::Skugga.Core.IMockSetup)new {className}());
        }}");
            }
            else if (isAutoScribe)
            {
                sb.AppendLine($@"        public static T Capture<T>(T instance) where T : class
        {{
            var proxy = new Skugga_RecordingProxy_{symbol.Name}_{stableHash}(({fullTypeName})instance!);
            return (T)(object)proxy;
        }}");
            }
            else if (target.Type == TargetType.Repository)
            {
                if (target.Overload == CreateOverload.Behavior)
                {
                    sb.AppendLine($@"        public static T Create<T>(this global::Skugga.Core.MockRepository repository, global::Skugga.Core.MockBehavior? behavior = null)
        {{
            var mock = (T)(object)new {className}(behavior ?? repository.Behavior);
            repository.Register(mock);
            return mock;
        }}");
                }
                else if (target.Overload == CreateOverload.DefaultValue)
                {
                    sb.AppendLine($@"        public static T Create<T>(this global::Skugga.Core.MockRepository repository, global::Skugga.Core.DefaultValue defaultValue)
        {{
            var mock = (T)(object)new {className}(repository.Behavior, defaultValue);
            repository.Register(mock);
            return mock;
        }}");
                }
                else if (target.Overload == CreateOverload.BehaviorAndDefaultValue)
                {
                    sb.AppendLine($@"        public static T Create<T>(this global::Skugga.Core.MockRepository repository, global::Skugga.Core.MockBehavior behavior, global::Skugga.Core.DefaultValue defaultValue)
        {{
            var mock = (T)(object)new {className}(behavior, defaultValue);
            repository.Register(mock);
            return mock;
        }}");
                }
            }
            else if (target.Type == TargetType.MockOf)
            {
                sb.AppendLine($@"        public static T Of<T>(global::System.Linq.Expressions.Expression<global::System.Func<T, bool>> predicate) where T : class
        {{
            var mock = (T)(object)new {className}(global::Skugga.Core.MockBehavior.Loose);
            global::Skugga.Core.LinqToMocks.ApplyFromExpression(mock, predicate);
            return mock;
        }}");
            }
            else
            {
                // Mock.Create
                if (target.Overload == CreateOverload.Behavior)
                {
                    sb.AppendLine($@"        public static T Create<T>(global::Skugga.Core.MockBehavior behavior = global::Skugga.Core.MockBehavior.Loose)
        {{
            return (T)(object)new {className}(behavior);
        }}");
                }
                else if (target.Overload == CreateOverload.DefaultValue)
                {
                    sb.AppendLine($@"        public static T Create<T>(global::Skugga.Core.DefaultValue defaultValue)
        {{
            return (T)(object)new {className}(defaultValue);
        }}");
                }
                else if (target.Overload == CreateOverload.BehaviorAndDefaultValue)
                {
                    sb.AppendLine($@"        public static T Create<T>(global::Skugga.Core.MockBehavior behavior, global::Skugga.Core.DefaultValue defaultValue)
        {{
            return (T)(object)new {className}(behavior, defaultValue);
        }}");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{interceptorClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
