#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using static Skugga.Generator.GeneratorHelpers;

namespace Skugga.Generator
{
    internal static class RecordingProxyGenerator
    {
        public static void GenerateRecordingProxy(SourceProductionContext spc, TargetInfo target)
        {
            var symbol = target.Symbol;
            if (symbol == null) return;

            var stableHash = GetStableHash(symbol.ToDisplayString());
            var className = $"Skugga_RecordingProxy_{symbol.Name}_{stableHash}";
            var baseType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var interfaceName = symbol.Name;
            var inheritance = $"{baseType}, Skugga.Core.IMockSetup";

            var sb = new StringBuilder(4096);
            sb.AppendLine(AutoGeneratedComment);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("#pragma warning disable CS8603 // Possible null reference return");
            sb.AppendLine(SystemUsing);
            sb.AppendLine(SkuggaCoreUsing);
            sb.AppendLine();
            sb.AppendLine(SkuggaGeneratedNamespace);
            sb.AppendLine("{");
            sb.Append("    public class ");
            sb.Append(className);
            sb.Append(" : ");
            sb.AppendLine(inheritance);
            sb.AppendLine("    {");
            sb.Append("        ");
            sb.AppendLine(MockHandlerField);
            sb.Append("        ");
            sb.AppendLine(HandlerProperty);
            sb.AppendLine($"        private readonly {baseType} _real;");
            sb.AppendLine("        private readonly List<string> _callLog = new();");
            sb.AppendLine("        private int _callCount = 1;");
            sb.AppendLine();

            sb.Append("        public ");
            sb.Append(className);
            sb.Append($"({baseType} instance)");
            sb.AppendLine("        {");
            sb.AppendLine("            _real = instance;");
            sb.AppendLine("        }");
            sb.AppendLine();

            GenerateMethods(sb, symbol, baseType);
            AutoScribeCodeGenerator.GenerateSerializeValueMethod(sb);
            AutoScribeCodeGenerator.GeneratePrintTestMethod(sb, interfaceName);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void GenerateMethods(StringBuilder sb, INamedTypeSymbol symbol, string baseType)
        {
            foreach (var method in GetAllMethods(symbol))
            {
                if (method.MethodKind != MethodKind.Ordinary) continue;

                var accessibility = "public";
                var modifierStr = "";
                var typeParams = "";
                var typeConstraints = "";
                if (method.IsGenericMethod)
                {
                    var typeParamNames = string.Join(", ", method.TypeParameters.Select(tp => tp.Name));
                    typeParams = $"<{typeParamNames}>";
                }

                var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                // Add async modifier if returning Task
                var returnTypeName = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (returnTypeName.StartsWith("global::System.Threading.Tasks.Task") ||
                    returnTypeName.StartsWith("global::System.Threading.Tasks.ValueTask"))
                {
                    modifierStr += "async ";
                }
                var paramList = string.Join(", ", method.Parameters.Select(p =>
                {
                    var refKind = p.RefKind == RefKind.Out ? "out " : p.RefKind == RefKind.Ref ? "ref " : p.RefKind == RefKind.In ? "in " : "";
                    return $"{refKind}{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}";
                }));

                sb.AppendLine();
                sb.Append("        ");
                sb.Append(accessibility);
                sb.Append(' ');
                sb.Append(modifierStr);
                sb.Append(returnType);
                sb.Append(' ');
                sb.Append(method.Name);
                sb.Append(typeParams);
                sb.Append('(');
                sb.Append(paramList);
                sb.Append(')');
                sb.AppendLine(typeConstraints);
                sb.AppendLine("        {");

                AutoScribeCodeGenerator.GenerateMethodRecording(sb, method, returnType);

                sb.AppendLine("        }");
            }
        }
    }
}
