using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.OpenApi.Models;

namespace Skugga.OpenApi.Generator
{
    /// <summary>
    /// Generates mock class implementations from OpenAPI interfaces.
    /// Creates classes with methods that return realistic data from OpenAPI examples.
    /// </summary>
    internal class MockGenerator
    {
        private readonly OpenApiDocument _document;
        private readonly TypeMapper _typeMapper;
        private readonly ExampleGenerator _exampleGenerator;
        private readonly bool _generateAsync;
        private readonly bool _enableStateful;
        private readonly bool _enableValidation;
        private readonly bool _enableAuth;
        private readonly IDictionary<string, OpenApiSecurityScheme> _securitySchemes;

        public MockGenerator(OpenApiDocument document, TypeMapper typeMapper, ExampleGenerator exampleGenerator, bool generateAsync = true, bool enableStateful = false, bool enableValidation = false, bool enableAuth = false, IDictionary<string, OpenApiSecurityScheme>? securitySchemes = null)
        {
            _document = document ?? throw new ArgumentNullException(nameof(document));
            _typeMapper = typeMapper ?? throw new ArgumentNullException(nameof(typeMapper));
            _exampleGenerator = exampleGenerator ?? throw new ArgumentNullException(nameof(exampleGenerator));
            _generateAsync = generateAsync;
            _enableStateful = enableStateful;
            _enableValidation = enableValidation;
            _enableAuth = enableAuth;
            _securitySchemes = securitySchemes ?? new Dictionary<string, OpenApiSecurityScheme>();
        }

        /// <summary>
        /// Generates a mock implementation class for an interface.
        /// </summary>
        public string GenerateMock(string interfaceName, string namespaceName, string? operationFilter = null, System.Collections.Generic.List<(string Name, string Modifiers)>? containingTypes = null)
        {
            var sb = new StringBuilder();
            var mockClassName = $"{interfaceName}Mock";

            // File header
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// This file is generated by SkuggaOpenApiGenerator");
            sb.AppendLine("// DO NOT EDIT: Changes will be overwritten on next build");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();

            // Namespace
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // Generate containing type declarations if nested
            int nestingLevel = 1;
            if (containingTypes != null && containingTypes.Any())
            {
                foreach (var (name, modifiers) in containingTypes)
                {
                    var indent = new string(' ', nestingLevel * 4);
                    sb.AppendLine($"{indent}{modifiers} {name}");
                    sb.AppendLine($"{indent}{{");
                    nestingLevel++;
                }
            }

            var classIndent = new string(' ', nestingLevel * 4);

            // Class declaration with XML doc
            sb.AppendLine($"{classIndent}/// <summary>");
            sb.AppendLine($"{classIndent}/// Auto-generated mock implementation of {interfaceName}.");
            sb.AppendLine($"{classIndent}/// Returns realistic data from OpenAPI specification examples.");
            if (_enableStateful)
            {
                sb.AppendLine($"{classIndent}/// Supports stateful CRUD operations with in-memory entity tracking.");
            }
            sb.AppendLine($"{classIndent}/// </summary>");
            sb.AppendLine($"{classIndent}/// <remarks>");
            sb.AppendLine($"{classIndent}/// This mock can be used directly for testing without Skugga.Core.");
            sb.AppendLine($"{classIndent}/// For advanced mocking features (Setup, Verify, Callbacks), use Mock.Create&lt;T&gt;().");
            if (_enableStateful)
            {
                sb.AppendLine($"{classIndent}/// Stateful behavior: POST creates entities, GET retrieves them, PUT/PATCH updates, DELETE removes.");
                sb.AppendLine($"{classIndent}/// Use ResetState() to clear all state between tests.");
            }
            sb.AppendLine($"{classIndent}/// </remarks>");
            sb.AppendLine($"{classIndent}public class {mockClassName} : {interfaceName}");
            sb.AppendLine($"{classIndent}{{");

            // Generate state storage if stateful
            if (_enableStateful)
            {
                GenerateStateStorage(sb, nestingLevel);
                sb.AppendLine();
            }

            // Generate auth state and methods if auth is enabled
            if (_enableAuth)
            {
                GenerateAuthState(sb, nestingLevel);
                sb.AppendLine();
            }

            // Generate method implementations
            var operations = GetOperations(operationFilter);
            

            foreach (var (operation, path, method) in operations)
            {
                GenerateMethodImplementation(sb, operation, path, method, nestingLevel);
                sb.AppendLine();
            }

            // Generate ResetState method if stateful
            if (_enableStateful)
            {
                GenerateResetStateMethod(sb, nestingLevel);
            }

            // Generate auth configuration and token methods if enabled
            if (_enableAuth)
            {
                GenerateAuthMethods(sb, nestingLevel);
            }

            // Close class
            sb.AppendLine($"{classIndent}}}");

            // Close containing types if nested
            if (containingTypes != null && containingTypes.Any())
            {
                for (int i = containingTypes.Count - 1; i >= 0; i--)
                {
                    nestingLevel--;
                    var indent = new string(' ', nestingLevel * 4);
                    sb.AppendLine($"{indent}}}");
                }
            }

            // Close namespace
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a single method implementation with realistic return value.
        /// </summary>
        private void GenerateMethodImplementation(StringBuilder sb, OpenApiOperation operation, string path, string httpMethod, int nestingLevel = 1)
        {
            var baseIndent = new string(' ', (nestingLevel + 1) * 4);
            var bodyIndent = new string(' ', (nestingLevel + 2) * 4);
            var methodName = GetMethodName(operation, path, httpMethod);
            var returnType = GetReturnType(operation, out var schema, out var mediaType, out var response);
            var hasHeaders = response?.Headers != null && response.Headers.Any();
            var parameters = GetParameters(operation);
            var isAsync = ShouldBeAsync(operation);
            var finalReturnType = isAsync && returnType != "void" ? $"Task<{returnType}>" : 
                                  isAsync ? "Task" : returnType;

            // Detect CRUD operation for stateful behavior
            var crudOp = _enableStateful ? DetectCrudOperation(httpMethod, path) : "OTHER";
            var entityType = _enableStateful ? GetEntityTypeName(path, returnType) : null;
            var idParam = _enableStateful ? GetIdParameterName(path) : null;

            // XML documentation
            sb.AppendLine($"{baseIndent}/// <summary>");
            sb.AppendLine($"{baseIndent}/// {EscapeXmlDoc(operation.Summary ?? $"{httpMethod.ToUpper()} {path}")}");
            sb.AppendLine($"{baseIndent}/// </summary>");

            // Method signature
            sb.Append($"{baseIndent}public {finalReturnType} {methodName}(");
            if (parameters.Any())
            {
                sb.Append(string.Join(", ", parameters.Select(p => $"{p.Type} {p.Name}")));
            }
            sb.AppendLine(")");

            // Method body
            sb.AppendLine($"{baseIndent}{{");

            // Auth validation if enabled and operation requires security
            if (_enableAuth && operation.Security != null && operation.Security.Any())
            {
                sb.AppendLine($"{bodyIndent}// Validate authentication");
                sb.AppendLine($"{bodyIndent}ValidateAuth();");
                sb.AppendLine();
            }

            // Stateful logic
            if (_enableStateful && crudOp != "OTHER" && returnType != "void" && schema != null)
            {
                // Get request body schema for stateful operations
                OpenApiSchema? requestBodySchema = null;
                if (operation.RequestBody?.Content?.FirstOrDefault(c => c.Key.Contains("json")).Value?.Schema != null)
                {
                    requestBodySchema = operation.RequestBody.Content.First(c => c.Key.Contains("json")).Value.Schema;
                }
                GenerateStatefulMethodBody(sb, crudOp, entityType, idParam, returnType, schema, requestBodySchema, mediaType, response, isAsync, parameters, bodyIndent, hasHeaders);
            }
            else
            {
                // Non-stateful logic (original behavior)
                GenerateStatelessMethodBody(sb, returnType, schema, mediaType, response, isAsync, bodyIndent, hasHeaders);
            }

            sb.AppendLine($"{baseIndent}}}");
        }

        /// <summary>
        /// Generates stateless method body (original behavior).
        /// </summary>
        private void GenerateStatelessMethodBody(StringBuilder sb, string returnType, OpenApiSchema? schema, OpenApiMediaType? mediaType, OpenApiResponse? response, bool isAsync, string bodyIndent, bool hasHeaders)
        {
            // Generate return statement with realistic data
            if (returnType != "void" && schema != null)
            {
                if (hasHeaders)
                {
                    // Extract body type from ApiResponse<T>
                    var bodyType = returnType.Replace("Skugga.Core.ApiResponse<", "").TrimEnd('>');
                    var bodyValue = _exampleGenerator.GenerateDefaultValue(schema, bodyType, mediaType);
                    
                    // Generate headers dictionary
                    sb.AppendLine($"{bodyIndent}var headers = new System.Collections.Generic.Dictionary<string, string>");
                    sb.AppendLine($"{bodyIndent}{{");
                    foreach (var header in response!.Headers)
                    {
                        var headerValue = GetHeaderValue(header.Value);
                        sb.AppendLine($"{bodyIndent}    {{ \"{header.Key}\", \"{EscapeString(headerValue)}\" }},");
                    }
                    sb.AppendLine($"{bodyIndent}}};");
                    
                    // Generate validation if enabled
                    if (_enableValidation)
                    {
                        sb.AppendLine($"{bodyIndent}var result = {bodyValue};");
                        GenerateValidationCode(sb, "result", bodyType, schema, bodyIndent);
                    }
                    
                    // Return ApiResponse
                    if (isAsync)
                    {
                        var resultValue = _enableValidation ? "result" : bodyValue;
                        sb.AppendLine($"{bodyIndent}return Task.FromResult(new {returnType}({resultValue}, headers));");
                    }
                    else
                    {
                        var resultValue = _enableValidation ? "result" : bodyValue;
                        sb.AppendLine($"{bodyIndent}return new {returnType}({resultValue}, headers);");
                    }
                }
                else
                {
                    // No headers - return body directly
                    var defaultValue = _exampleGenerator.GenerateDefaultValue(schema, returnType, mediaType);
                    
                    // Generate validation if enabled
                    if (_enableValidation)
                    {
                        sb.AppendLine($"{bodyIndent}var result = {defaultValue};");
                        GenerateValidationCode(sb, "result", returnType, schema, bodyIndent);
                    }
                    
                    if (isAsync)
                    {
                        var resultValue = _enableValidation ? "result" : defaultValue;
                        // Add explicit type argument if defaultValue is null for proper type inference
                        if (!_enableValidation && (defaultValue == "null" || defaultValue == "null!" || defaultValue == "default"))
                        {
                            sb.AppendLine($"{bodyIndent}return Task.FromResult<{returnType}>(null!);");
                        }
                        else
                        {
                            sb.AppendLine($"{bodyIndent}return Task.FromResult({resultValue});");
                        }
                    }
                    else
                    {
                        var resultValue = _enableValidation ? "result" : defaultValue;
                        sb.AppendLine($"{bodyIndent}return {resultValue};");
                    }
                }
            }
            else if (returnType != "void")
            {
                // Fallback if no schema available
                if (isAsync)
                {
                    sb.AppendLine($"{bodyIndent}return Task.FromResult(default({returnType})!);");
                }
                else
                {
                    sb.AppendLine($"{bodyIndent}return default({returnType})!;");
                }
            }
            else if (isAsync)
            {
                sb.AppendLine($"{bodyIndent}return Task.CompletedTask;");
            }
        }

        /// <summary>
        /// Generates stateful method body with CRUD logic.
        /// </summary>
        private void GenerateStatefulMethodBody(StringBuilder sb, string crudOp, string? entityType, string? idParam, string returnType, OpenApiSchema responseSchema, OpenApiSchema? requestBodySchema, OpenApiMediaType? mediaType, OpenApiResponse? response, bool isAsync, List<ParameterInfo> parameters, string bodyIndent, bool hasHeaders)
        {
            var innerIndent = bodyIndent + "    ";
            
            // Check if there's a body parameter
            var hasBodyParam = parameters.Any(p => p.Name == "body");
            var bodyParamType = hasBodyParam ? parameters.First(p => p.Name == "body").Type : null;

            switch (crudOp)
            {
                case "CREATE":
                    // POST - Create new entity
                    sb.AppendLine($"{bodyIndent}lock (_stateLock)");
                    sb.AppendLine($"{bodyIndent}{{");
                    sb.AppendLine($"{innerIndent}// Get or create entity store");
                    sb.AppendLine($"{innerIndent}if (!_entityStore.ContainsKey(\"{entityType}\"))");
                    sb.AppendLine($"{innerIndent}{{");
                    sb.AppendLine($"{innerIndent}    _entityStore[\"{entityType}\"] = new System.Collections.Generic.Dictionary<string, object>();");
                    sb.AppendLine($"{innerIndent}    _idCounters[\"{entityType}\"] = 1;");
                    sb.AppendLine($"{innerIndent}}}");
                    sb.AppendLine();
                    sb.AppendLine($"{innerIndent}// Generate new ID");
                    sb.AppendLine($"{innerIndent}var newId = _idCounters[\"{entityType}\"]++;");
                    sb.AppendLine();
                    if (hasBodyParam && requestBodySchema != null)
                    {
                        sb.AppendLine($"{innerIndent}// Create entity from body data with generated ID");
                        sb.Append($"{innerIndent}var entity = new {returnType} {{ ");
                        
                        // Add ID assignment (assuming first property is ID or contains "id")
                        var properties = responseSchema.Properties ?? new Dictionary<string, OpenApiSchema>();
                        var idProperty = properties.FirstOrDefault(p => p.Key.ToLowerInvariant().Contains("id")).Key;
                        if (!string.IsNullOrEmpty(idProperty))
                        {
                            var idSchema = properties[idProperty];
                            var idValue = idSchema.Type == "string" ? "newId.ToString()" : "newId";
                            sb.Append($"{ToPascalCase(idProperty)} = {idValue}, ");
                        }
                        
                        // Add common properties from body
                        var bodyProperties = requestBodySchema.Properties ?? new Dictionary<string, OpenApiSchema>();
                        foreach (var prop in bodyProperties)
                        {
                            if (properties.ContainsKey(prop.Key))
                            {
                                sb.Append($"{ToPascalCase(prop.Key)} = body.{ToPascalCase(prop.Key)}, ");
                            }
                        }
                        
                        // Remove trailing comma and space if present
                        var currentLine = sb.ToString();
                        if (currentLine.EndsWith(", "))
                        {
                            sb.Length -= 2;
                        }
                        
                        sb.AppendLine(" };");
                    }
                    else
                    {
                        sb.AppendLine($"{innerIndent}// Create entity with generated ID and parameter/example data");
                        var entityCreation = GenerateEntityFromParameters(parameters, responseSchema, returnType, mediaType, idParam);
                        sb.AppendLine($"{innerIndent}var entity = {entityCreation};");
                    }
                    sb.AppendLine();
                    sb.AppendLine($"{innerIndent}// Store entity");
                    sb.AppendLine($"{innerIndent}_entityStore[\"{entityType}\"][newId.ToString()] = entity!;");
                    sb.AppendLine();
                    sb.AppendLine($"{innerIndent}// Return created entity");
                    if (isAsync)
                    {
                        sb.AppendLine($"{innerIndent}return Task.FromResult(({returnType})entity!);");
                    }
                    else
                    {
                        sb.AppendLine($"{innerIndent}return ({returnType})entity!;");
                    }
                    sb.AppendLine($"{bodyIndent}}}");
                    break;

                case "READ_ONE":
                    // GET /resource/{id} - Retrieve single entity
                    var idParamName = idParam != null ? ToCamelCase(idParam) : "id";
                    sb.AppendLine($"{bodyIndent}lock (_stateLock)");
                    sb.AppendLine($"{bodyIndent}{{");
                    sb.AppendLine($"{innerIndent}// Check if entity store exists");
                    sb.AppendLine($"{innerIndent}if (!_entityStore.ContainsKey(\"{entityType}\"))");
                    sb.AppendLine($"{innerIndent}{{");
                    sb.AppendLine($"{innerIndent}    throw new System.InvalidOperationException($\"Entity '{entityType}' with id {{{idParamName}}} not found (404)\");");
                    sb.AppendLine($"{innerIndent}}}");
                    sb.AppendLine();
                    sb.AppendLine($"{innerIndent}// Retrieve entity");
                    sb.AppendLine($"{innerIndent}if (_entityStore[\"{entityType}\"].TryGetValue({idParamName}?.ToString() ?? \"\", out var entity))");
                    sb.AppendLine($"{innerIndent}{{");
                    if (isAsync)
                    {
                        sb.AppendLine($"{innerIndent}    return Task.FromResult(({returnType})entity);");
                    }
                    else
                    {
                        sb.AppendLine($"{innerIndent}    return ({returnType})entity;");
                    }
                    sb.AppendLine($"{innerIndent}}}");
                    sb.AppendLine();
                    sb.AppendLine($"{innerIndent}throw new System.InvalidOperationException($\"Entity '{entityType}' with id {{{idParamName}}} not found (404)\");");
                    sb.AppendLine($"{bodyIndent}}}");
                    break;

                case "READ_ALL":
                    // GET /resource - Retrieve all entities
                    sb.AppendLine($"{bodyIndent}lock (_stateLock)");
                    sb.AppendLine($"{bodyIndent}{{");
                    sb.AppendLine($"{innerIndent}// Return all entities or empty list");
                    sb.AppendLine($"{innerIndent}if (!_entityStore.ContainsKey(\"{entityType}\"))");
                    sb.AppendLine($"{innerIndent}{{");
                    var emptyList = returnType.Contains("[]") ? $"new {returnType.Replace("[]", "[0]")}" : 
                                   returnType.Contains("IEnumerable") || returnType.Contains("List") ? 
                                   $"new System.Collections.Generic.List<{GetGenericTypeArgument(returnType)}>()" : 
                                   _exampleGenerator.GenerateDefaultValue(responseSchema, returnType, mediaType);
                    if (isAsync)
                    {
                        sb.AppendLine($"{innerIndent}    return Task.FromResult({emptyList});");
                    }
                    else
                    {
                        sb.AppendLine($"{innerIndent}    return {emptyList};");
                    }
                    sb.AppendLine($"{innerIndent}}}");
                    sb.AppendLine();
                    var itemType = GetGenericTypeArgument(returnType);
                    sb.AppendLine($"{innerIndent}var entities = _entityStore[\"{entityType}\"].Values.Cast<{itemType}>().ToList();");
                    if (returnType.Contains("[]"))
                    {
                        // Return as array
                        if (isAsync)
                        {
                            sb.AppendLine($"{innerIndent}return Task.FromResult(({returnType})entities.ToArray());");
                        }
                        else
                        {
                            sb.AppendLine($"{innerIndent}return ({returnType})entities.ToArray();");
                        }
                    }
                    else
                    {
                        // Return as list or enumerable
                        if (isAsync)
                        {
                            sb.AppendLine($"{innerIndent}return Task.FromResult(({returnType})entities);");
                        }
                        else
                        {
                            sb.AppendLine($"{innerIndent}return ({returnType})entities;");
                        }
                    }
                    sb.AppendLine($"{bodyIndent}}}");
                    break;

                case "UPDATE":
                    // PUT/PATCH /resource/{id} - Update entity (create if not exists)
                    idParamName = idParam != null ? ToCamelCase(idParam) : "id";
                    sb.AppendLine($"{bodyIndent}lock (_stateLock)");
                    sb.AppendLine($"{bodyIndent}{{");
                    sb.AppendLine($"{innerIndent}// Get or create entity store");
                    sb.AppendLine($"{innerIndent}if (!_entityStore.ContainsKey(\"{entityType}\"))");
                    sb.AppendLine($"{innerIndent}{{");
                    sb.AppendLine($"{innerIndent}    _entityStore[\"{entityType}\"] = new System.Collections.Generic.Dictionary<string, object>();");
                    sb.AppendLine($"{innerIndent}}}");
                    sb.AppendLine();
                    if (hasBodyParam && requestBodySchema != null)
                    {
                        sb.AppendLine($"{innerIndent}// Get existing entity or create new one");
                        sb.AppendLine($"{innerIndent}var existing = _entityStore[\"{entityType}\"].ContainsKey({idParamName}?.ToString() ?? \"\")");
                        sb.AppendLine($"{innerIndent}    ? ({returnType})_entityStore[\"{entityType}\"][{idParamName}?.ToString() ?? \"\"]");
                        
                        // Create new entity with ID - need to handle type conversion
                        var idProperty = (responseSchema.Properties ?? new Dictionary<string, OpenApiSchema>()).FirstOrDefault(p => p.Key.ToLowerInvariant().Contains("id")).Key;
                        var idSchema = responseSchema.Properties?[idProperty];
                        var idAssignment = idSchema?.Type == "string" ? $"Id = {idParamName}" : $"Id = int.Parse({idParamName})";
                        sb.AppendLine($"{innerIndent}    : new {returnType} {{ {idAssignment} }};");
                        sb.AppendLine();
                        // Add property assignments
                        var bodyProperties = requestBodySchema.Properties ?? new Dictionary<string, OpenApiSchema>();
                        var responseProperties = responseSchema.Properties ?? new Dictionary<string, OpenApiSchema>();
                        
                        foreach (var prop in bodyProperties)
                        {
                            if (responseProperties.ContainsKey(prop.Key))
                            {
                                sb.AppendLine($"{innerIndent}existing.{ToPascalCase(prop.Key)} = body.{ToPascalCase(prop.Key)};");
                            }
                        }
                        
                        sb.AppendLine($"{innerIndent}var updated = existing;");
                        sb.AppendLine($"{innerIndent}_entityStore[\"{entityType}\"][{idParamName}?.ToString() ?? \"\"] = updated;");
                    }
                    else
                    {
                        sb.AppendLine($"{innerIndent}// Update entity with parameter/example data");
                        if (returnType != "void")
                        {
                            var entityCreation = GenerateEntityFromParameters(parameters, responseSchema, returnType, mediaType, idParam);
                            sb.AppendLine($"{innerIndent}var updated = {entityCreation};");
                            sb.AppendLine($"{innerIndent}_entityStore[\"{entityType}\"][{idParamName}?.ToString() ?? \"\"] = updated!;");
                        }
                        else
                        {
                            // For void returns, just create a dummy entity for storage
                            sb.AppendLine($"{innerIndent}var updated = new System.Collections.Generic.Dictionary<string, object>();");
                            sb.AppendLine($"{innerIndent}_entityStore[\"{entityType}\"][{idParamName}?.ToString() ?? \"\"] = updated;");
                        }
                    }
                    if (returnType != "void")
                    {
                        if (isAsync)
                        {
                            sb.AppendLine($"{innerIndent}return Task.FromResult(({returnType})updated!);");
                        }
                        else
                        {
                            sb.AppendLine($"{innerIndent}return ({returnType})updated!;");
                        }
                    }
                    else if (isAsync)
                    {
                        sb.AppendLine($"{innerIndent}return Task.CompletedTask;");
                    }
                    sb.AppendLine($"{bodyIndent}}}");
                    break;

                case "DELETE":
                    // DELETE /resource/{id} - Delete entity
                    idParamName = idParam != null ? ToCamelCase(idParam) : "id";
                    sb.AppendLine($"{bodyIndent}lock (_stateLock)");
                    sb.AppendLine($"{bodyIndent}{{");
                    sb.AppendLine($"{innerIndent}// Check if entity exists");
                    sb.AppendLine($"{innerIndent}if (!_entityStore.ContainsKey(\"{entityType}\") || !_entityStore[\"{entityType}\"].Remove({idParamName}?.ToString() ?? \"\"))");
                    sb.AppendLine($"{innerIndent}{{");
                    sb.AppendLine($"{innerIndent}    throw new System.InvalidOperationException($\"Entity '{entityType}' with id {{{idParamName}}} not found (404)\");");
                    sb.AppendLine($"{innerIndent}}}");
                    sb.AppendLine();
                    if (returnType != "void")
                    {
                        if (isAsync)
                        {
                            sb.AppendLine($"{innerIndent}return Task.FromResult(default({returnType})!);");
                        }
                        else
                        {
                            sb.AppendLine($"{innerIndent}return default({returnType})!;");
                        }
                    }
                    else if (isAsync)
                    {
                        sb.AppendLine($"{innerIndent}return Task.CompletedTask;");
                    }
                    sb.AppendLine($"{bodyIndent}}}");
                    break;

                default:
                    // Fallback to stateless
                    GenerateStatelessMethodBody(sb, returnType, responseSchema, mediaType, response, isAsync, bodyIndent, hasHeaders);
                    break;
            }
        }

        /// <summary>
        /// Extracts generic type argument from collection types (e.g., List&lt;User&gt; -> User).
        /// </summary>
        private string GetGenericTypeArgument(string type)
        {
            var startIndex = type.IndexOf('<');
            if (startIndex < 0) return "object";
            
            var endIndex = type.LastIndexOf('>');
            if (endIndex < 0) return "object";
            
            return type.Substring(startIndex + 1, endIndex - startIndex - 1);
        }

        /// <summary>
        /// Determines if an operation should be async based on configuration.
        /// </summary>
        private bool ShouldBeAsync(OpenApiOperation operation)
        {
            return _generateAsync;
        }

        /// <summary>
        /// Generates a method name from operation ID or path/method.
        /// </summary>
        private string GetMethodName(OpenApiOperation operation, string path, string httpMethod)
        {
            if (!string.IsNullOrEmpty(operation.OperationId))
            {
                return ToPascalCase(operation.OperationId);
            }

            var cleanPath = path.Replace("/", "_").Replace("{", "").Replace("}", "").Trim('_');
            return ToPascalCase($"{httpMethod}_{cleanPath}");
        }

        /// <summary>
        /// Gets the return type and schema for an operation (unwrapped, Task added separately).
        /// </summary>
        private string GetReturnType(OpenApiOperation operation, out OpenApiSchema? schema, out OpenApiMediaType? mediaType, out OpenApiResponse? response)
        {
            schema = null;
            mediaType = null;
            response = null;

            var successResponse = operation.Responses?.FirstOrDefault(r =>
                r.Key == "200" || r.Key == "201" || r.Key == "202" || r.Key == "204" || r.Key == "default").Value;

            if (successResponse == null)
                return "void";

            response = successResponse;

            // Try multiple JSON content types in order of preference
            // 1. application/json (standard)
            // 2. application/*+json (e.g., application/vnd.api+json)
            // 3. text/json (legacy)
            // 4. Any content type with "json" in the name
            // 5. First content type with a schema (fallback for Swagger 2.0 conversion)
            var content = successResponse.Content?.FirstOrDefault(c => c.Key == "application/json").Value
                ?? successResponse.Content?.FirstOrDefault(c => c.Key.StartsWith("application/") && c.Key.EndsWith("+json")).Value
                ?? successResponse.Content?.FirstOrDefault(c => c.Key == "text/json").Value
                ?? successResponse.Content?.FirstOrDefault(c => c.Key.Contains("json")).Value
                ?? successResponse.Content?.FirstOrDefault(c => c.Value?.Schema != null).Value;

            if (content?.Schema == null)
                return "void";

            schema = content.Schema;
            mediaType = content;

            var bodyType = _typeMapper.MapType(schema);

            // Check if response has headers - if so, wrap in ApiResponse<T>
            if (successResponse.Headers != null && successResponse.Headers.Any())
            {
                return $"Skugga.Core.ApiResponse<{bodyType}>";
            }

            return bodyType;
        }

        /// <summary>
        /// Gets parameters for an operation, including request body.
        /// </summary>
        private List<ParameterInfo> GetParameters(OpenApiOperation operation)
        {
            var result = new List<ParameterInfo>();

            // Add path and query parameters first
            if (operation.Parameters != null)
            {
                foreach (var param in operation.Parameters)
                {
                    var paramType = param.Schema != null
                        ? _typeMapper.MapType(param.Schema, null, !param.Required)
                        : "object";

                    result.Add(new ParameterInfo
                    {
                        Name = ToCamelCase(param.Name),
                        Type = paramType
                    });
                }
            }

            // Add request body parameter last
            if (operation.RequestBody != null)
            {
                var content = operation.RequestBody.Content?.FirstOrDefault(c => c.Key.Contains("json")).Value;
                if (content?.Schema != null)
                {
                    var bodyType = _typeMapper.MapType(content.Schema, null, !operation.RequestBody.Required);
                    result.Add(new ParameterInfo
                    {
                        Name = "body",
                        Type = bodyType
                    });
                }
            }

            return result;
        }

        /// <summary>
        /// Gets all operations from the document, optionally filtered by tags.
        /// </summary>
        private List<(OpenApiOperation Operation, string Path, string Method)> GetOperations(string? operationFilter)
        {
            var result = new List<(OpenApiOperation, string, string)>();

            if (_document.Paths == null)
                return result;

            foreach (var path in _document.Paths)
            {
                // Check if path.Value or path.Value.Operations is null
                if (path.Value == null || path.Value.Operations == null)
                    continue;

                foreach (var operation in path.Value.Operations)
                {
                    var op = operation.Value;
                    
                    // Skip if operation is null
                    if (op == null)
                        continue;

                    // Apply tag filter if specified
                    if (operationFilter != null)
                    {
                        var filterTags = operationFilter.Split(',')
                            .Select(t => t.Trim().ToLowerInvariant())
                            .ToArray();
                        
                        if (op.Tags == null || op.Tags.Count == 0 || !op.Tags.Any(t =>
                            t != null && t.Name != null && filterTags.Contains(t.Name.ToLowerInvariant())))
                        {
                            continue;
                        }
                    }

                    result.Add((op, path.Key, operation.Key.ToString().ToLower()));
                }
            }

            return result;
        }

        /// <summary>
        /// Converts a string to PascalCase.
        /// </summary>
        private string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;

            // If input is already PascalCase or camelCase (no delimiters), just ensure first char is uppercase
            if (!input.Contains('_') && !input.Contains('-') && !input.Contains(' '))
            {
                return char.ToUpperInvariant(input[0]) + (input.Length > 1 ? input.Substring(1) : "");
            }

            // Handle snake_case, kebab-case, space separated
            var parts = input.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    if (part.Length > 1)
                        sb.Append(part.Substring(1).ToLowerInvariant());
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Extracts the header value from an OpenApiHeader.
        /// </summary>
        private string GetHeaderValue(Microsoft.OpenApi.Models.OpenApiHeader header)
        {
            // Try to get example from schema first
            if (header.Schema?.Example != null)
            {
                var example = header.Schema.Example;
                // Handle OpenApiInteger, OpenApiString, etc.
                if (example is Microsoft.OpenApi.Any.OpenApiInteger intExample)
                    return intExample.Value.ToString();
                if (example is Microsoft.OpenApi.Any.OpenApiString strExample)
                    return strExample.Value;
                if (example is Microsoft.OpenApi.Any.OpenApiDouble dblExample)
                    return dblExample.Value.ToString();
                if (example is Microsoft.OpenApi.Any.OpenApiBoolean boolExample)
                    return boolExample.Value.ToString().ToLower();
                if (example is Microsoft.OpenApi.Any.OpenApiLong longExample)
                    return longExample.Value.ToString();
            }

            // Try header-level example
            if (header.Example != null)
            {
                var example = header.Example;
                if (example is Microsoft.OpenApi.Any.OpenApiInteger intExample)
                    return intExample.Value.ToString();
                if (example is Microsoft.OpenApi.Any.OpenApiString strExample)
                    return strExample.Value;
                if (example is Microsoft.OpenApi.Any.OpenApiDouble dblExample)
                    return dblExample.Value.ToString();
                if (example is Microsoft.OpenApi.Any.OpenApiBoolean boolExample)
                    return boolExample.Value.ToString().ToLower();
                if (example is Microsoft.OpenApi.Any.OpenApiLong longExample)
                    return longExample.Value.ToString();
            }

            // Fallback to default value based on schema type
            return GetDefaultHeaderValue(header.Schema);
        }

        /// <summary>
        /// Gets a default header value based on schema type.
        /// </summary>
        private string GetDefaultHeaderValue(OpenApiSchema? schema)
        {
            if (schema == null)
                return "value";

            return schema.Type?.ToLowerInvariant() switch
            {
                "integer" => "0",
                "number" => "0.0",
                "boolean" => "false",
                "string" => "value",
                _ => "value"
            };
        }

        /// <summary>
        /// Escapes a string for use in C# string literals.
        /// </summary>
        private string EscapeString(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "";
            
            return input.Replace("\\", "\\\\")
                        .Replace("\"", "\\\"")
                        .Replace("\n", "\\n")
                        .Replace("\r", "\\r")
                        .Replace("\t", "\\t");
        }

        /// <summary>
        /// Converts a string to camelCase.
        /// </summary>
        private string ToCamelCase(string input)
        {
            var pascal = ToPascalCase(input);
            if (string.IsNullOrEmpty(pascal))
                return pascal;

            return char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);
        }

        /// <summary>
        /// Escapes XML documentation text.
        /// </summary>
        private string EscapeXmlDoc(string text)
        {
            if (string.IsNullOrEmpty(text))
                return string.Empty;

            return text.Replace("&", "&amp;")
                       .Replace("<", "&lt;")
                       .Replace(">", "&gt;")
                       .Replace("\"", "&quot;")
                       .Replace("'", "&apos;");
        }

        /// <summary>
        /// Generates state storage fields for stateful mocking.
        /// </summary>
        private void GenerateStateStorage(StringBuilder sb, int nestingLevel)
        {
            var baseIndent = new string(' ', (nestingLevel + 1) * 4);
            
            sb.AppendLine($"{baseIndent}/// <summary>");
            sb.AppendLine($"{baseIndent}/// In-memory storage for stateful mock entities. Dictionary key is the entity type name.");
            sb.AppendLine($"{baseIndent}/// </summary>");
            sb.AppendLine($"{baseIndent}private readonly System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, object>> _entityStore = new();");
            sb.AppendLine();
            
            sb.AppendLine($"{baseIndent}/// <summary>");
            sb.AppendLine($"{baseIndent}/// Counter for generating unique IDs per entity type.");
            sb.AppendLine($"{baseIndent}/// </summary>");
            sb.AppendLine($"{baseIndent}private readonly System.Collections.Generic.Dictionary<string, int> _idCounters = new();");
            sb.AppendLine();
            
            sb.AppendLine($"{baseIndent}/// <summary>");
            sb.AppendLine($"{baseIndent}/// Lock object for thread-safe state operations.");
            sb.AppendLine($"{baseIndent}/// </summary>");
            sb.AppendLine($"{baseIndent}private readonly object _stateLock = new();");
        }

        /// <summary>
        /// Generates the ResetState method for clearing mock state.
        /// </summary>
        private void GenerateResetStateMethod(StringBuilder sb, int nestingLevel)
        {
            var baseIndent = new string(' ', (nestingLevel + 1) * 4);
            var bodyIndent = new string(' ', (nestingLevel + 2) * 4);
            
            sb.AppendLine($"{baseIndent}/// <summary>");
            sb.AppendLine($"{baseIndent}/// Resets all stateful mock data. Call between tests for isolation.");
            sb.AppendLine($"{baseIndent}/// </summary>");
            sb.AppendLine($"{baseIndent}public void ResetState()");
            sb.AppendLine($"{baseIndent}{{");
            sb.AppendLine($"{bodyIndent}lock (_stateLock)");
            sb.AppendLine($"{bodyIndent}{{");
            sb.AppendLine($"{bodyIndent}    _entityStore.Clear();");
            sb.AppendLine($"{bodyIndent}    _idCounters.Clear();");
            sb.AppendLine($"{bodyIndent}}}");
            sb.AppendLine($"{baseIndent}}}");
        }

        /// <summary>
        /// Detects HTTP method type for stateful behavior determination.
        /// </summary>
        private string DetectCrudOperation(string httpMethod, string path)
        {
            var method = httpMethod.ToUpperInvariant();
            
            // Check if path has an ID parameter (e.g., /users/{id})
            var hasIdParam = path.Contains("{") && path.Contains("}");
            
            if (method == "POST") return "CREATE";
            if (method == "GET" && hasIdParam) return "READ_ONE";
            if (method == "GET" && !hasIdParam) return "READ_ALL";
            if (method == "PUT" && hasIdParam) return "UPDATE";
            if (method == "PATCH" && hasIdParam) return "UPDATE";
            if (method == "DELETE" && hasIdParam) return "DELETE";
            
            return "OTHER";
        }

        /// <summary>
        /// Extracts the entity type name from the path (e.g., /users/{id} -> User).
        /// </summary>
        private string GetEntityTypeName(string path, string returnType)
        {
            // Remove leading slash and split by /
            var parts = path.TrimStart('/').Split('/');
            
            // Get the first segment (e.g., "users" from "/users/{id}")
            var segment = parts.Length > 0 ? parts[0] : "Entity";
            
            // Convert plural to singular (basic heuristic)
            if (segment.EndsWith("ies"))
                segment = segment.Substring(0, segment.Length - 3) + "y";
            else if (segment.EndsWith("es"))
                segment = segment.Substring(0, segment.Length - 2);
            else if (segment.EndsWith("s"))
                segment = segment.Substring(0, segment.Length - 1);
            
            // PascalCase
            return ToPascalCase(segment);
        }

        /// <summary>
        /// Extracts ID parameter name from path (e.g., /users/{id} -> id, /users/{userId} -> userId).
        /// </summary>
        private string? GetIdParameterName(string path)
        {
            var startIndex = path.IndexOf('{');
            if (startIndex < 0) return null;
            
            var endIndex = path.IndexOf('}', startIndex);
            if (endIndex < 0) return null;
            
            return path.Substring(startIndex + 1, endIndex - startIndex - 1);
        }

        /// <summary>
        /// Generates runtime validation code for a response value.
        /// </summary>
        private void GenerateValidationCode(StringBuilder sb, string varName, string typeName, OpenApiSchema schema, string indent)
        {
            sb.AppendLine($"{indent}// Runtime contract validation");
            sb.AppendLine($"{indent}if ({varName} != null)");
            sb.AppendLine($"{indent}{{");
            
            var innerIndent = indent + "    ";
            
            // Required properties
            var requiredProps = schema.Required?.ToArray();
            if (requiredProps != null && requiredProps.Length > 0)
            {
                var requiredArray = string.Join(", ", requiredProps.Select(p => $"\"{p}\""));
                sb.AppendLine($"{innerIndent}Skugga.Core.Validation.SchemaValidator.ValidateRequiredProperties({varName}, \"{typeName}\", new[] {{ {requiredArray} }});");
            }
            
            // Type validation for arrays
            if (schema.Type == "array" && schema.Items != null)
            {
                var itemType = _typeMapper.MapType(schema.Items);
                var itemRequired = schema.Items.Required?.Select(r => $"\"{r}\"").ToArray();
                var itemRequiredParam = itemRequired != null && itemRequired.Length > 0 
                    ? $", new[] {{ {string.Join(", ", itemRequired)} }}" 
                    : ", null";
                    
                sb.AppendLine($"{innerIndent}Skugga.Core.Validation.SchemaValidator.ValidateArray({varName}, \"{typeName}\", typeof({itemType}){itemRequiredParam});");
            }
            
            // Enum validation
            if (schema.Enum != null && schema.Enum.Count > 0)
            {
                var enumValues = schema.Enum.Select(e => $"\"{e}\"");
                sb.AppendLine($"{innerIndent}Skugga.Core.Validation.SchemaValidator.ValidateValue({varName}, typeof({typeName}), \"{typeName}\", null, new[] {{ {string.Join(", ", enumValues)} }});");
            }
            
            sb.AppendLine($"{indent}}}");
        }

        /// <summary>
        /// Generates auth state fields for authentication mocking.
        /// </summary>
        private void GenerateAuthState(StringBuilder sb, int nestingLevel = 1)
        {
            var indent = new string(' ', (nestingLevel + 1) * 4);
            
            sb.AppendLine($"{indent}// Authentication state");
            sb.AppendLine($"{indent}private bool _tokenExpired = false;");
            sb.AppendLine($"{indent}private bool _tokenInvalid = false;");
            sb.AppendLine($"{indent}private bool _credentialsRevoked = false;");
            sb.AppendLine($"{indent}private readonly object _authLock = new object();");
        }

        /// <summary>
        /// Generates authentication configuration and token generation methods.
        /// </summary>
        private void GenerateAuthMethods(StringBuilder sb, int nestingLevel = 1)
        {
            var indent = new string(' ', (nestingLevel + 1) * 4);
            var bodyIndent = new string(' ', (nestingLevel + 2) * 4);

            // ConfigureSecurity method
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Configures authentication behavior for testing scenarios.");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}/// <param name=\"tokenExpired\">Simulate expired token (401).</param>");
            sb.AppendLine($"{indent}/// <param name=\"tokenInvalid\">Simulate invalid token (401).</param>");
            sb.AppendLine($"{indent}/// <param name=\"credentialsRevoked\">Simulate revoked credentials (403).</param>");
            sb.AppendLine($"{indent}public void ConfigureSecurity(bool tokenExpired = false, bool tokenInvalid = false, bool credentialsRevoked = false)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{bodyIndent}lock (_authLock)");
            sb.AppendLine($"{bodyIndent}{{");
            sb.AppendLine($"{bodyIndent}    _tokenExpired = tokenExpired;");
            sb.AppendLine($"{bodyIndent}    _tokenInvalid = tokenInvalid;");
            sb.AppendLine($"{bodyIndent}    _credentialsRevoked = credentialsRevoked;");
            sb.AppendLine($"{bodyIndent}}}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // Determine which auth schemes are present
            var hasOAuth2 = _securitySchemes.Any(s => s.Value?.Type == SecuritySchemeType.OAuth2);
            var hasBearer = _securitySchemes.Any(s => s.Value?.Type == SecuritySchemeType.Http && 
                                                       s.Value?.Scheme?.Equals("bearer", StringComparison.OrdinalIgnoreCase) == true);
            var hasApiKey = _securitySchemes.Any(s => s.Value?.Type == SecuritySchemeType.ApiKey);
            var hasBasic = _securitySchemes.Any(s => s.Value?.Type == SecuritySchemeType.Http && 
                                                      s.Value?.Scheme?.Equals("basic", StringComparison.OrdinalIgnoreCase) == true);

            // Generate token generation method for OAuth2/Bearer
            if (hasOAuth2 || hasBearer)
            {
                sb.AppendLine($"{indent}/// <summary>");
                sb.AppendLine($"{indent}/// Generates a mock access token (Bearer JWT format).");
                sb.AppendLine($"{indent}/// </summary>");
                sb.AppendLine($"{indent}/// <returns>Mock JWT token in Bearer format.</returns>");
                sb.AppendLine($"{indent}public string GenerateAccessToken()");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{bodyIndent}// Generate mock JWT token (header.payload.signature)");
                sb.AppendLine($"{bodyIndent}var headerJson = \"{{\\\"alg\\\":\\\"HS256\\\",\\\"typ\\\":\\\"JWT\\\"}}\";");
                sb.AppendLine($"{bodyIndent}var exp = System.DateTimeOffset.UtcNow.AddHours(1).ToUnixTimeSeconds();");
                sb.AppendLine($"{bodyIndent}var payloadJson = \"{{\\\"sub\\\":\\\"user123\\\",\\\"exp\\\":\" + exp + \"}}\";");
                sb.AppendLine($"{bodyIndent}var header = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(headerJson));");
                sb.AppendLine($"{bodyIndent}var payload = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(payloadJson));");
                sb.AppendLine($"{bodyIndent}var signature = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(\"mock-signature\"));");
                sb.AppendLine($"{bodyIndent}return $\"Bearer {{header}}.{{payload}}.{{signature}}\";");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }

            // Generate API key generation method
            if (hasApiKey)
            {
                sb.AppendLine($"{indent}/// <summary>");
                sb.AppendLine($"{indent}/// Generates a mock API key.");
                sb.AppendLine($"{indent}/// </summary>");
                sb.AppendLine($"{indent}/// <returns>Mock API key string.</returns>");
                sb.AppendLine($"{indent}public string GenerateApiKey()");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{bodyIndent}return $\"sk_test_{{System.Guid.NewGuid():N}}\";");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }

            // Generate basic auth credentials method
            if (hasBasic)
            {
                sb.AppendLine($"{indent}/// <summary>");
                sb.AppendLine($"{indent}/// Generates mock Basic authentication credentials.");
                sb.AppendLine($"{indent}/// </summary>");
                sb.AppendLine($"{indent}/// <returns>Base64-encoded username:password.</returns>");
                sb.AppendLine($"{indent}public string GenerateBasicAuth()");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{bodyIndent}var credentials = \"user:password\";");
                sb.AppendLine($"{bodyIndent}var encoded = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(credentials));");
                sb.AppendLine($"{bodyIndent}return $\"Basic {{encoded}}\";");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }

            // Generate validation helper method
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Validates authentication state before processing operation.");
            sb.AppendLine($"{indent}/// Throws UnauthorizedException or ForbiddenException based on configured state.");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}private void ValidateAuth()");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{bodyIndent}lock (_authLock)");
            sb.AppendLine($"{bodyIndent}{{");
            sb.AppendLine($"{bodyIndent}    if (_tokenExpired || _tokenInvalid)");
            sb.AppendLine($"{bodyIndent}    {{");
            sb.AppendLine($"{bodyIndent}        throw new System.UnauthorizedAccessException(_tokenExpired ? \"Token expired\" : \"Invalid token\");");
            sb.AppendLine($"{bodyIndent}    }}");
            sb.AppendLine($"{bodyIndent}    if (_credentialsRevoked)");
            sb.AppendLine($"{bodyIndent}    {{");
            sb.AppendLine($"{bodyIndent}        throw new System.UnauthorizedAccessException(\"Credentials revoked\");");
            sb.AppendLine($"{bodyIndent}    }}");
            sb.AppendLine($"{bodyIndent}}}");
            sb.AppendLine($"{indent}}}");
        }

        /// <summary>
        /// Generates code to create an entity from method parameters and example data.
        /// Honors parameter values where they match response schema properties.
        /// </summary>
        private string GenerateEntityFromParameters(List<ParameterInfo> parameters, OpenApiSchema responseSchema, string returnType, OpenApiMediaType? mediaType, string? idParam)
        {
            var sb = new StringBuilder();
            sb.Append($"new {returnType} {{ ");

            // Add ID assignment (assuming first property is ID or contains "id")
            var properties = responseSchema.Properties ?? new Dictionary<string, OpenApiSchema>();
            var idProperty = properties.FirstOrDefault(p => p.Key.ToLowerInvariant().Contains("id")).Key;
            if (!string.IsNullOrEmpty(idProperty))
            {
                var idSchema = properties[idProperty];
                var idValue = idSchema.Type == "string" ? "newId.ToString()" : "newId";
                sb.Append($"{ToPascalCase(idProperty)} = {idValue}, ");
            }

            // Add parameter values for matching properties
            foreach (var param in parameters)
            {
                // Skip the body parameter (already handled above) and ID parameters
                if (param.Name == "body" || param.Name == ToCamelCase(idParam ?? "")) continue;

                // Check if response schema has a matching property (case-insensitive)
                var matchingProperty = properties.FirstOrDefault(p => 
                    p.Key.Equals(param.Name, StringComparison.OrdinalIgnoreCase) ||
                    ToPascalCase(p.Key).Equals(ToPascalCase(param.Name), StringComparison.OrdinalIgnoreCase));

                if (!string.IsNullOrEmpty(matchingProperty.Key))
                {
                    sb.Append($"{ToPascalCase(matchingProperty.Key)} = {param.Name}, ");
                }
            }

            // For any remaining properties, use example data by generating a temporary object
            var exampleValue = _exampleGenerator.GenerateDefaultValue(responseSchema, returnType, mediaType);
            if (!string.IsNullOrEmpty(exampleValue) && exampleValue.StartsWith("new "))
            {
                // Extract property assignments from example
                var exampleProps = ExtractPropertyAssignments(exampleValue);
                foreach (var prop in exampleProps)
                {
                    // Only add if not already added above
                    var propName = prop.Key;
                    var alreadyAdded = sb.ToString().Contains($"{ToPascalCase(propName)} = ");
                    if (!alreadyAdded)
                    {
                        sb.Append($"{propName} = {prop.Value}, ");
                    }
                }
            }

            // Remove trailing comma and space
            var result = sb.ToString().TrimEnd(',', ' ');
            result += " }";

            return result;
        }

        /// <summary>
        /// Extracts property assignments from generated example code.
        /// </summary>
        private Dictionary<string, string> ExtractPropertyAssignments(string exampleCode)
        {
            var assignments = new Dictionary<string, string>();
            
            // Simple parsing of "new Type { Prop1 = value1, Prop2 = value2 }"
            var startIndex = exampleCode.IndexOf('{');
            var endIndex = exampleCode.LastIndexOf('}');
            
            if (startIndex >= 0 && endIndex > startIndex)
            {
                var propsPart = exampleCode.Substring(startIndex + 1, endIndex - startIndex - 1);
                var propAssignments = propsPart.Split(',');
                
                foreach (var assignment in propAssignments)
                {
                    var trimmed = assignment.Trim();
                    if (trimmed.Contains(" = "))
                    {
                        var parts = trimmed.Split(new[] { " = " }, 2, StringSplitOptions.None);
                        if (parts.Length == 2)
                        {
                            assignments[parts[0].Trim()] = parts[1].Trim();
                        }
                    }
                }
            }
            
            return assignments;
        }

        private class ParameterInfo
        {
            public string Name { get; set; } = string.Empty;
            public string Type { get; set; } = string.Empty;
        }
    }
}
